name: CreativeControl
main: com.spoontacular.creativecontrol.CreativeControl
version: 0.0.1
commands:
   cr:
      description: Switch the player to creative mode.
      usage: /cr
      permission-message: You don't have creativecontrol.cr